---
title: "cleanin and feature engineerin"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidytext)
library(wordcloud2)
library(tidyverse)
```

```{r}
# read data
dat <- read.csv("tinderdata.csv", header = T, stringsAsFactors = F, allowEscapes = FALSE)
```

```{r}
# read data
dat <- read.delim("tinderdata.txt", header = T, stringsAsFactors = F, allowEscapes = FALSE)
```

```{r}
# clean up the html
dat[,1] <- str_remove_all(dat[,1], "<.*?>")
dat[,2] <- str_remove_all(dat[,2], "<.*?>")
dat[,3] <- str_remove_all(dat[,3], "<.*?>")
dat[,3] <- str_replace_all(dat[,3], "[\n]", " ")
dat[,3] <- str_replace_all(dat[,3], "â???T", "'")
dat[,3] <- str_replace_all(dat[,3], "&amp;", "and")
# change encoding to remove emojis and certain hieroglyphs
Encoding(dat[,3]) <- "latin1"
dat[,3] <- iconv(dat[,3], "latin1", "ASCII", sub="")
Encoding(dat[,1]) <- "latin1"
dat[,1] <- iconv(dat[,1], "latin1", "ASCII", sub="[]")
```

```{r}
# replace duplicates just in case - just 1
indices <- c()
for (i in seq_len(nrow(dat))[-1]) {
  if (sum(dat[i,] == dat[i-1,])==3) {
    indices <- c(indices, i)
  }
}

dat <- dat[-indices,]

# remove the rows where ages were hidden
indices <- which(is.na(as.numeric(dat[,2])))
dat <- dat[-indices,]

dat[,2] <- as.numeric(dat[,2])

# change names
names(dat) <- c("name", "age", "info")

# save as dat0 incase i ever want to get get back to this stage
dat0 <- dat
```

```{r}
# random things to add as columns

# included height in bio
dat <- dat %>% 
  mutate(inclheight = grepl("\\d'\\d+", dat[,3]) * 1)
which(dat$inclheight==1)
dat$inclheight <- str_extract(dat[,3],"\\d'\\d+")

# instagram tags
dat$igtag <- str_extract(dat[,3],"@\\S+")
dat$igtag[512] <- "@angelicachastang"

# info length (not counting emojis)
dat$infolen <- nchar(dat$info)

# mention horoscope
dat$horoscope <- str_extract(tolower(dat[,3]),"\\bgemini\\b|\\baries\\b|\\btaurus\\b|\\bcancer\\b|\\bleo\\b|\\bvirgo\\b|\\blibra\\b|\\bscorpio\\b|\\bsagittarius\\b|\\bcapricorn\\b|\\baquarius\\b|\\bpisces\\b")
```

```{r}
# write to file
write.csv(dat, file="cleantinder.csv", row.names = F)
```
